name: data_pipeline_development

on:
  push:
    branches:
      - dev

jobs:
  test-glue-jobs:
    name: Run Glue Job in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for Docker Compose
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
          echo "WORKSPACE_LOCATION=${{ github.workspace }}" >> .env


      - name: Start Glue PySpark container
        run: docker compose -f docker-compose.yml up -d glue_pyspark

      - name: Wait for container healthcheck
        run: |
          echo "Waiting for container to become healthy..."
          for i in {1..10}; do
            status=$(docker inspect --format='{{json .State.Health.Status}}' $(docker ps -qf name=glue_pyspark))
            if [ "$status" = "\"healthy\"" ]; then
              echo "Container is healthy!"
              break
            fi
            echo "Waiting... ($i)"
            sleep 5
          done
          
      - name: Install openpyxl in container
        run: docker compose exec glue_pyspark pip install openpyxl

      - name: Debug AWS identity inside container
        run: docker compose exec glue_pyspark aws sts get-caller-identity

      - name:  Test Glue job - extraction.py
        run: docker compose exec glue_pyspark spark-submit /home/glue_user/workspace/glue_jobs/extraction.py

      - name: Run Glue job - data_ingestion.py
        run: docker compose exec glue_pyspark spark-submit /home/glue_user/workspace/glue_jobs/data_ingestion.py

      - name: Run Glue job - data_transformation.py
        run: docker compose exec glue_pyspark spark-submit /home/glue_user/workspace/glue_jobs/data_transformation.py  

      - name: Stop and clean up containers
        if: always()
        run: docker compose -f docker-compose.yml down --volumes
